ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 72, in get
    return HttpResponse(f.read())
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 304: character maps to <undefined>
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 72, in get
    return HttpResponse(f.read())
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 304: character maps to <undefined>
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 72, in get
    return HttpResponse(f.read())
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 304: character maps to <undefined>
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 72, in get
    return HttpResponse(f.read())
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 304: character maps to <undefined>
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:django.request:Internal Server Error: /post_parser/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 72, in get
    return HttpResponse(f.read())
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 304: character maps to <undefined>
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 72, in get
    return HttpResponse(f.read())
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 304: character maps to <undefined>
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\PostParser\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\PostParser\settings.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:django.request:Internal Server Error: /post_parser/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 72, in get
    return HttpResponse(f.read())
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 304: character maps to <undefined>
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:django.request:Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 72, in get
    return HttpResponse(f.read())
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 304: character maps to <undefined>
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
WARNING:django.request:Bad Request: /user/login/
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
WARNING:django.request:Forbidden: /posts/get/
WARNING:django.request:Forbidden: /posts/get/
WARNING:django.request:Forbidden: /posts/get/
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\PostParser\settings.py changed, reloading.
WARNING:django.request:Forbidden: /posts/get/
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
WARNING:django.request:Bad Request: /posts/get/
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 55, in get_posts
    resp = self.vk.method("groups.getById", {"group_ids": group_ids})
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\vk_api\vk_api.py", line 646, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: group_ids is undefined
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 55, in get_posts
    resp = self.vk.method("groups.getById", {"group_ids": ",".join(group_ids)})
TypeError: sequence item 0: expected str instance, int found
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 57, in get_posts
    for i in range(group_ids):
TypeError: 'list' object cannot be interpreted as an integer
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 58, in get_posts
    group_posts[i]["group_name"] = group_ids[i]["name"]
TypeError: string indices must be integers
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 60, in get_posts
    group_posts[i]["group_name"] = resp[i]["name"]
IndexError: list index out of range
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 61, in get_posts
    group_posts[i]["group_name"] = resp[i]["name"]
IndexError: list index out of range
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 61, in get_posts
    group_posts[i]["group_name"] = resp[i]["name"]
IndexError: list index out of range
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 61, in get_posts
    group_posts[i]["group_name"] = resp[i]["name"]
IndexError: list index out of range
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 61, in get_posts
    group_posts[i]["group_name"] = resp[i]["name"]
IndexError: list index out of range
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 37, in get_posts
    print(resp['response'])
KeyError: 'response'
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 56, in get_posts
    resp = self.vk.method("groups.getById", {"group_ids": ",".join(group_ids[j:i])})
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\vk_api\vk_api.py", line 646, in method
    raise error
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: group_ids is undefined
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 75, in get_posts
    group_posts[i]["group_name"] = resp[i]["name"]
IndexError: list index out of range
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 75, in get_posts
    group_posts[i]["group_name"] = resp[i]["name"]
IndexError: list index out of range
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 42, in get_posts
    named_item["name"] = resp["groups"][i]
KeyError: 'groups'
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 43, in get_posts
    named_item["name"] = resp["groups"][i]
KeyError: 'groups'
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 43, in get_posts
    named_item["name"] = resp["groups"][i]
IndexError: list index out of range
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:django.request:Internal Server Error: /posts/get/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\views.py", line 51, in get
    posts = bot.get_posts(q, start_time, end_time, count, extended)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 49, in get_posts
    named_item["name"] = self.get_name_from_id(str(named_item["owner_id"]), resp["groups"])
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py", line 21, in get_name_from_id
    raise ValueError
ValueError
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\poster\vk_bot.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\admin.py changed, reloading.
ERROR:django.request:Internal Server Error: /admin/user/userip/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\options.py", line 581, in get_field
    return self.fields_map[field_name]
KeyError: 'amount_ips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 262, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 293, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\options.py", line 583, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: UserIP has no field named 'amount_ips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 342, in result_list
    'results': list(results(cl)),
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 232, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 273, in lookup_field
    attr = getattr(obj, name)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py", line 9, in amount_ips
    return len(self.ips)
TypeError: object of type 'RelatedManager' has no len()
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:django.request:Internal Server Error: /admin/user/userip/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\options.py", line 581, in get_field
    return self.fields_map[field_name]
KeyError: 'amount_ips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 262, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 293, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\options.py", line 583, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: UserIP has no field named 'amount_ips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 342, in result_list
    'results': list(results(cl)),
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 232, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 275, in lookup_field
    value = attr()
TypeError: __init__() missing 1 required positional argument: 'instance'
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:django.request:Internal Server Error: /admin/user/userip/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 342, in result_list
    'results': list(results(cl)),
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 241, in items_for_result
    result_repr = display_for_value(value, empty_value_display, boolean)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 421, in display_for_value
    return str(value)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py", line 12, in __str__
    return self.user.username
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 196, in __get__
    raise self.RelatedObjectDoesNotExist(
user.models.UserIP.user.RelatedObjectDoesNotExist: UserIP has no user.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:django.request:Internal Server Error: /admin/user/userip/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 342, in result_list
    'results': list(results(cl)),
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 241, in items_for_result
    result_repr = display_for_value(value, empty_value_display, boolean)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 421, in display_for_value
    return str(value)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py", line 12, in __str__
    return self.username
AttributeError: 'UserIP' object has no attribute 'username'
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:django.request:Internal Server Error: /admin/user/userip/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 342, in result_list
    'results': list(results(cl)),
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 241, in items_for_result
    result_repr = display_for_value(value, empty_value_display, boolean)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 421, in display_for_value
    return str(value)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py", line 12, in __str__
    return self.user.username
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 196, in __get__
    raise self.RelatedObjectDoesNotExist(
user.models.UserIP.user.RelatedObjectDoesNotExist: UserIP has no user.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:django.request:Internal Server Error: /admin/user/userip/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\options.py", line 581, in get_field
    return self.fields_map[field_name]
KeyError: 'amount_ips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 262, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 293, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\options.py", line 583, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: UserIP has no field named 'amount_ips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 342, in result_list
    'results': list(results(cl)),
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 232, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 273, in lookup_field
    attr = getattr(obj, name)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py", line 9, in amount_ips
    print(type(len(self.ips)))
TypeError: object of type 'RelatedManager' has no len()
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:django.request:Internal Server Error: /admin/user/userip/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\options.py", line 581, in get_field
    return self.fields_map[field_name]
KeyError: 'amount_ips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 262, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 293, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\options.py", line 583, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: UserIP has no field named 'amount_ips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 342, in result_list
    'results': list(results(cl)),
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 232, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\contrib\admin\utils.py", line 273, in lookup_field
    attr = getattr(obj, name)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py", line 9, in amount_ips
    for ip in self.ips:
TypeError: 'RelatedManager' object is not iterable
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\urls.py changed, reloading.
WARNING:django.request:Bad Request: /user/login/
WARNING:django.request:Bad Request: /user/login/
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
WARNING:django.request:Forbidden: /user/after_login/
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /user/after_login/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'UserIP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py", line 51, in get
    ip_instance = IP.objects.get_or_create(user=user_ip, ip=ip)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 404, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1166, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <UserIP: UserIP object (1)>.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /user/after_login/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'UserIP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py", line 51, in get
    ip_instance = IP.objects.get_or_create(user=user_ip, ip=ip)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 404, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1166, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <UserIP: UserIP object (1)>.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /user/after_login/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py", line 51, in get
    ip_instance = IP.objects.get_or_create(user=user_ip.id, ip=ip)
AttributeError: 'tuple' object has no attribute 'id'
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /user/after_login/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'UserIP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py", line 51, in get
    ip_instance = IP.objects.get_or_create(user=user_ip, ip=ip)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 404, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1166, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <UserIP: UserIP object (1)>.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /user/after_login/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1772, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'UserIP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py", line 52, in get
    ip_instance = IP.objects.get_or_create(user=user_ip, ip=ip)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 404, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\sql\query.py", line 1166, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\lookups.py", line 22, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <UserIP: UserIP object (1)>.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:django.request:Internal Server Error: /user/after_login/
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 415, in get
    raise self.model.DoesNotExist(
user.models.UserIP.DoesNotExist: UserIP matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py", line 50, in get
    user_ip, _ = UserIP.objects.get_or_create(user=user.id)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 562, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 596, in _create_object_from_params
    obj = self.create(**params)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\query.py", line 431, in create
    obj = self.model(**kwargs)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\base.py", line 482, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 309, in __set__
    super().__set__(instance, value)
  File "C:\Users\admin\Desktop\freelance\PostParser\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 214, in __set__
    raise ValueError(
ValueError: Cannot assign "3": "UserIP.user" must be a "User" instance.
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
INFO:django.utils.autoreload:C:\Users\admin\Desktop\freelance\PostParser\PostParser\user\views.py changed, reloading.
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
ERROR:root:C:\Users\admin\Desktop\freelance\PostParser\PostParser\post_parser_react\build\index.html
NoneType: None
ERROR:root:it's open
NoneType: None
